#!/usr/bin/env python3
# -*- mode: python; coding: utf-8 -*-
"""
Usage: trims [OPTIONS] [SERVICES [SERVICES …]]

positional arguments:
  SERVICES              services(5) compliant input file

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         show version information and exit
  -c, --copyright       show copying policy and exit
  -o OUTPUT, --output OUTPUT
                        resultant services(5) compliant file

Trims trims one or more services(5) compliant files such that
the result has exactly one line for each unique port/protocol
combination. In short, a union of all combinations seen.

If no filenames are given on the commandline, or if the pseudo
filename ‘-’ is used, standard input is assumed.

Services from files that appear later on the commandline takes
presedence over data from earlier files. In this case earlier
service names are moved to the aliases list.

The result is written to standard output unless an output file
is given explicitly, using the ‘-o’ / ‘--ouput’ option.
"""
##############################################################################
# This program is free software; you can redistribute it and/or modify it    #
# under the terms of the GNU General Public License as published by the Free #
# Software Foundation; either version 3 of the License, or (at your option)  #
# any later version.                                                         #
#                                                                            #
# This program is distributed in the hope that it will be useful, but with-  #
# out any warranty; without even the implied warranty of merchantability or  #
# fitness for a particular purpose. See the GNU General Public License for   #
# more details.  <http://gplv3.fsf.org/>                                     #
##############################################################################

import sys
import os
import argparse
import pathlib
import re

from types import SimpleNamespace
from collections import namedtuple
from datetime import datetime
from pprint import pprint

try:
    from locale import (Error, setlocale, LC_ALL)
    _ = setlocale(LC_ALL, '')
except (ImportError, ModuleNotFoundError, NameError, Error):
    pass

__author__ = 'Klaus Alexander Seistrup <klaus@seistrup.dk>'
__whoami__ = 'trims'
__revision__ = '2017-03-11'
__version__ = '0.0.3α ({})'.format(__revision__)
__copyright__ = """
trims {}

Copyright © 2017 Klaus Alexander Seistrup <klaus@seistrup.dk>

This is free software; see the source for copying conditions.
There is no warranty; not even for merchantability or fitness
for a particular purpose.

Issues to <https://github.com/kseistrup/trims/issues>, please.
""".format(__version__)

EPILOG = """
Trims trims one or more services(5) compliant files such that
the result has exactly one line for each unique port/protocol
combination. In short, a union of all combinations seen.

If no filenames are given on the commandline, or if the pseudo
filename ‘-’ is used, standard input is assumed.

Services from files that appear later on the commandline takes
presedence over data from earlier files. In this case earlier
service names are moved to the aliases list.

The result is written to standard output unless an output file
is given explicitly, using the ‘-o’ / ‘--ouput’ option.
"""
STDERR = sys.stderr
MINVER = (3, 4)  # Minimumversion of Python required
DEBUG = os.environ.get('DEBUG', 'False')[0].upper() in '1JTY'  # 1/Ja/True/Yes

# Protocol numbers for saner sorting, taken from /etc/protocols
PROTOS = dict(tcp='006', udp='017', dccp='033', sctp='132')

# Each service line has the format
#
#    name port/proto [alias [alias …]] [# comment]
#
# with TABs/SPACEs as separators. The easiest here is to
# treat aliases + comment together as a single entity:
SVCRX = re.compile(r'^(\S+)\s+(\d{1,5})/(\S+)\s*(.*)$')

FileDesc = namedtuple('filedesc', 'name path mode desc')


def debug(head, data=None):
    """Possibly pretty print an object to stderr"""
    if DEBUG:
        pprint(head if data is None else {head: data}, stream=STDERR)


def deuglify(error):
    """Deuglify the EnvironmentError class of errors"""
    debug('ugly', error)

    nargs = len(error.args)

    if nargs == 1:
        return str(error)

    if nargs == 2 and hasattr(error, 'strerror'):
        prettier = {
            '-': 'standard IO',
            '/dev/stdin': 'standard input',
            '/dev/stdout': 'standard output',
        }
        fname1 = fname2 = None

        if hasattr(error, 'filename'):
            fname1 = prettier.get(error.filename, error.filename,)
        if hasattr(error, 'filename2'):
            fname2 = prettier.get(error.filename2, error.filename2)

        if fname1 and fname2:
            return '{}: {} → {}'.format(error.strerror, fname1, fname2)
        if fname1 or fname2:
            return '{}: {}'.format(error.strerror, fname1 or fname2)

        return error.strerror

    # Let's not pretend that we know the nature on the exception
    return error


def die(error=None):
    """Exit gracefully"""
    debug('exit', error)

    if error:
        print(
            deuglify(error) if isinstance(error, Exception) else error,
            file=STDERR
        )
    sys.exit(1 if error else 0)


def filedesc(fname, mode=None):
    """Return a suitable Path object"""
    if not fname or fname == '-':
        fptr = {'r': sys.stdin, 'w': sys.stdout}.get(mode)
        desc = fptr.fileno()
        path = None
        name = fptr.name or {'r': '<stdin>', 'w': '<stdout>'}.get(mode)
    else:
        desc = None
        path = pathlib.Path(fname)
        name = path.resolve().as_posix()

    return FileDesc(name=name, path=path, mode=mode, desc=desc)


def is_fileish(fdesc):
    """Check if FPATH is a file, a FIFO or a character device"""
    debug('desc', fdesc)

    if fdesc.desc is not None and fdesc.desc > -1:
        return True

    fpath = fdesc.path

    if fpath is None:
        return False

    return fpath.is_file() or fpath.is_fifo() or fpath.is_char_device()


def fdopen(fdesc):
    """Open a FileDesc object and return a file pointer"""
    # A regular file
    if fdesc.path is not None:
        return open(fdesc.path.as_posix(), fdesc.mode)
    # StdIO
    if fdesc.desc is not None:
        return open(os.dup(fdesc.desc), fdesc.mode)

    die('Invalid file descriptor: {}'.format(fdesc))


def read_services(flist):
    """Trims Redundant Input, Merges Services → dict"""
    services = {}

    for fdesc in flist:
        with fdopen(fdesc) as fptr:
            lines = fptr.readlines()

        for line in map(lambda s: s.rstrip(), lines):
            # Skip empty, too short, and commented lines
            if len(line) < 5 or line.startswith('#'):
                continue

            match = SVCRX.match(line)

            if match is None:
                continue

            (port, proto) = (int(match.group(2)), match.group(3))
            (aliases, *comment) = match.group(4).split('#', 1)

            if port < 0 or port > 0xffff:
                continue  # Or should we just give a fsck?

            key = (port, PROTOS.get(proto, proto))
            val = SimpleNamespace(
                name=match.group(1),
                port=port,
                proto=proto,
                aliases=set(aliases.split()),
                comment=comment[0].strip() if comment else ''
            )

            if key in services:
                old = services[key]
                val.aliases.add(old.name)
                val.aliases.update(old.aliases)
                if not val.comment and old.comment:
                    val.comment = old.comment

            services.update({key: val})

    return services


def headers(fdesc, sources, headfoot=True):
    """Create a suitable header for out services file"""
    # We don't really use this,
    # but might in a later version
    if not headfoot:
        return []

    lines = ['# File:\n']

    lines.append('#   {}\n#\n'.format(fdesc.name))
    lines.append('# Created:\n')
    lines.append('#   {:%F %T}\n#\n'.format(datetime.now()))
    lines.append(
        '# Source{}:\n'.format(
            '' if len(list(set(sources))) == 1 else 's'
        )
    )
    cache = set()
    srcno = 0

    for source in sources:
        fname = source.name
        if fname not in cache:
            srcno += 1
            cache.add(fname)
            lines.append('#  {:>2d}. {}\n'.format(srcno, fname))

    lines.append('\n')

    return lines


def write_lines(fdesc, *array):
    """Write a bunch of lines to a file"""
    # Or should we write to an mkstemp() temporary
    # file that we rename and remove upon success?
    with fdopen(fdesc) as fptr:
        for lines in array:
            fptr.writelines(lines)


def write_service(fdesc, services, sources):
    """Write a services(5) compliant file according to services dictionary"""
    lines = []

    for (_, val) in sorted(services.items()):
        name = val.name
        port = '{:>5d}'.format(val.port)
        proto = val.proto
        alist = val.aliases
        alist.discard(name)
        aliases = ' '.join(sorted(alist))
        comment = '# {}'.format(val.comment) if val.comment else ''

        data = '{service} {port}/{proto}'.format(
            service='{:<15s}'.format(name),
            port=port,
            proto=proto
        )
        if not aliases and not comment:
            lines.append(data + '\n')
        else:
            elms = [data]
            if aliases:
                elms.append(aliases)
            if comment:
                elms.append(comment)
            lines.append('  '.join(elms) + '\n')

    eof = ['# EOF\n']

    if lines:
        eof.insert(0, '\n')

    write_lines(fdesc, headers(fdesc, sources), lines, eof)

    return 0


def check_files(files):
    """Check that a list of FileDesc()s are all valid"""
    for fdesc in files:
        if fdesc.desc is not None:
            if fdesc.desc > -1:
                continue
            error = 'Invalid file number {} for file {}'.format(
                fdesc.desc, fdesc.name
            )
            die(error)
        elif fdesc.path is not None:
            # If the file already exists, it should be file-like
            if fdesc.path.exists():
                # We can exclude directories right away
                if fdesc.path.is_dir():
                    die('Is a directory: {}'.format(fdesc.name))
                if is_fileish(fdesc):
                    continue
                error = 'Not a file, FIFO or character device: {}'.format(
                    fdesc.name
                )
                die(error)
            # If the file does not exist, it cannot be meant for reading
            if fdesc.mode == 'r':
                die('No such file: {}'.format(fdesc.name))
            # If the file does not exist and is meant for writing,
            # we'll check writeability later
        else:
            # No file handle and no file path? Something is wrong
            die('Internal error: {}'.format(fdesc))


def main(progname=__whoami__):
    """Main entry point"""
    if sys.version_info < MINVER:
        die('Python {0}.{1} required'.format(*MINVER))

    debug('argv', sys.argv)

    parser = argparse.ArgumentParser(
        prog=progname,
        formatter_class=argparse.RawTextHelpFormatter,
        epilog=EPILOG
    )
    # Generic options
    parser.add_argument('-v', '--version', action='version',
                        version='%(prog)s/{}'.format(__version__),
                        help='show version information and exit')
    parser.add_argument('-c', '--copyright', action='version',
                        version=__copyright__,
                        help='show copying policy and exit')
    # Specific options
    parser.add_argument('-o', '--output', default='-',
                        help='resultant services(5) compliant file')
    # Services files
    parser.add_argument('SERVICES', nargs='*',
                        help='services(5) compliant input file')

    args = parser.parse_args()
    debug('args', args)

    output = filedesc(args.output or '-', 'w')
    check_files([output])

    inputs = [filedesc(fname, 'r') for fname in args.SERVICES or ['-']]
    check_files(inputs)

    exitcode = 1

    try:
        services = read_services(inputs)
        exitcode = write_service(
            fdesc=output,
            services=services,
            sources=inputs
        )
    except (KeyboardInterrupt, BrokenPipeError):
        die()
    except (FileNotFoundError, PermissionError) as error:
        die(error)
    except IsADirectoryError as error:
        die(error)
    except (IOError, OSError, MemoryError) as error:
        die(error)

    return exitcode


if __name__ == '__main__':
    sys.exit(main(pathlib.Path(sys.argv[0]).name))

# eof
